Finish project
dolbilov/CalculatorWithTests pull request #3
Opened 2023-05-05 09:40 UTC by dolbilov

2023-05-05 13:33 UTC, Dikin01 commented on .github/workflows/dotnet.yml
> -    branches: [ "main" ]
тест

2023-05-05 13:37 UTC, Dikin01 commented on CalculatorBase/Interfaces/ICalculator.cs
> +    public static string ErrorsMessage = $"Absolute value of divider can't be less than {Epsilon:g2}";
ErrorMessage*, а лучше InvalidDividerValueMessage

2023-05-05 14:04 UTC, Dikin01 commented on Tests/MainWindowViewModelTests.cs
> +    public void Result_ShouldBeExpected_WhenSumTwoNumbers(double firstArgument, double secondArgument, string expected)
В этих тестах и тестах ниже не вижу смысла, ты и так модуль калькулятора проверяешь на правильность операций. Здесь максимум форматированный вывод проверить можно

2023-05-05 14:14 UTC, Dikin01 requested changes

2023-05-05 14:14 UTC, Dikin01 commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +        if (Math.Abs(SecondArgument) < ICalculator.Epsilon)
А в чём смысл тогда DivideByZeroException, если ты тоже самое условие тут проверяешь? Чисто для тестов что ли? 
Попробуй выполнить операцию в TryCatch и текст ошибки добавляй в AddError. Да, ты выполнишь операцию два раза, но тут обычное деление, а не парсинг 2 мб json. Потом буффер добавить можно если будет сложное что-то считать. Как вариант добавляй Validator отдельный для ICalculator и VM, либо прям валидацию в ICalculator пихай

2023-05-05 20:25 UTC, devTryer31 requested changes

2023-05-05 20:25 UTC, devTryer31 commented on Tests/MainWindowViewModelTests.cs
> +        (_vm.GetErrors(nameof(_vm.Result)) as ICollection)?.Should().NotBe(0);
Более того, непонятно почему `ICollection` 'не должен быть' 0. Видимо подразумевалось `ICollection?.Count`?

2023-05-05 20:25 UTC, devTryer31 commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +public class MainWindowViewModel : ViewModelBase, INotifyDataErrorInfo
Предлагаю перенести всё, что связано с ошибками, вынести в отдельную VM или класс, а в данной модели оставить свойство полученного объекта. Разделишь ответственность классов.

2023-05-05 20:25 UTC, devTryer31 commented on Tests/CalculatorTests.cs
> +    public void Divide_ShouldReturnExpected(double a, double b, double expected)
Что, если попадёт `double.PositiveInfinity NegativeInfinity`?

2023-05-06 06:59 UTC, dolbilov commented on CalculatorBase/Styles/ValidationStyles.axaml
> +                        <!-- ReSharper disable once Xaml.CompiledBindingMissingDataTypeErrorHighlighting -->
Да, нужен. Без него ReSharper выкидывает ошибку, которая не является ошибкой на самом деле.

2023-05-06 07:00 UTC, dolbilov commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +        this.WhenAnyValue(vm => vm.FirstArgument, vm => vm.SecondArgument, vm => vm.SelectedOperation)
Здесь this нужен, без него не работает.

2023-05-06 07:00 UTC, dolbilov commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +        set => this.RaiseAndSetIfChanged(ref _firstArgument, value);
Здесь this нужен, без него не работает.

2023-05-06 07:08 UTC, dolbilov commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +    private readonly Calculator _calculator = new();
Сделано.

2023-05-06 07:09 UTC, dolbilov commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +            .Subscribe(_ => DoCalculations());
Нет, так не работает(

2023-05-06 07:10 UTC, dolbilov commented on Tests/CalculatorTests.cs
> +    public void Divide_ShouldThrowException_WhenDividerLessThatEpsilon(double a, double b)
Поправил.

2023-05-06 07:14 UTC, dolbilov commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +    public IEnumerable GetErrors(string? propertyName = null)
К сожалению, это имплементация интерфейса. Я не могу поменять тип данных.

2023-05-06 07:16 UTC, dolbilov commented on CalculatorBase/Interfaces/ICalculator.cs
> +    public static string ErrorsMessage = $"Absolute value of divider can't be less than {Epsilon:g2}";
Сделано.

2023-05-06 07:18 UTC, dolbilov commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +        if (Math.Abs(SecondArgument) < ICalculator.Epsilon)
Поправил.

2023-05-06 07:19 UTC, dolbilov commented on Tests/CalculatorTests.cs
> +    public void Divide_ShouldThrowException_WhenDividerLessThatEpsilon(double a, double b)
Поправил.

2023-05-06 07:28 UTC, dolbilov commented on Tests/MainWindowViewModelTests.cs
> +        (_vm.GetErrors(nameof(_vm.Result)) as ICollection)?.Should().NotBe(0);
Non-generic IEnumerable не поддерживается LINQ. Нет ни метода Count, ни возможности преобразовать в List. Поэтому пришлось сделать такой каст.

2023-05-06 07:29 UTC, dolbilov commented on Tests/MainWindowViewModelTests.cs
> +        (_vm.GetErrors(nameof(_vm.Result)) as ICollection)?.Should().NotBe(0);
Действительно забыл Count. Поправил.

2023-05-06 07:41 UTC, dolbilov commented on Tests/Tests.csproj
> +        <PackageReference Include="coverlet.collector" Version="3.2.0">
Это плохо, что он в зависимостях?

2023-05-06 07:41 UTC, dolbilov commented on .github/workflows/dotnet.yml
> +          dotnet-version: 6.0.x
Да, все собирается прекрасно. Думаешь стоит обновиться?

2023-05-06 07:52 UTC, dolbilov commented on CalculatorBase/Interfaces/ICalculator.cs
> +    public const double Epsilon = 1e-6;
Думаешь стоит вынести это как поле в самом калькуляторе?

2023-05-06 08:51 UTC, dolbilov commented on Tests/CalculatorTests.cs
> +    public void Divide_ShouldReturnExpected(double a, double b, double expected)
Пользователь вводит эти данные в текстовые поля. Он не сможет вписать туда бесконечность.

2023-05-06 09:30 UTC, dolbilov commented on CalculatorBase/Styles/ValidationStyles.axaml
> +                            <Setter Property="Background" Value="LightPink" />
Конкретно здесь они используются всего один раз, не вижу смысла их выносить в данном случае. Но на будущее учту.

2023-05-06 10:46 UTC, devTryer31 commented on CalculatorBase/Interfaces/ICalculator.cs
> +    public const double Epsilon = 1e-6;
Или в базовый класс калькулятора

2023-05-06 11:04 UTC, Dikin01 commented on CalculatorBase/Interfaces/ICalculator.cs
> +    public const double Epsilon = 1e-6;
Так, что за суета. Надо понимать контекст, почему тут это константа. Контекст - лаба по тестированию в прошлом семестре. Где явно было требование в комментариях кода к этому интерфейсу значение, при котором у всех наследников должна быть точность епсилон. 
Вынести её в константу в этом же классе и убрать из комментов, а также добавить в константу текст ошибки форматирование бизнес требований, но не изменение.
Конечно, если бы не бизнес требования, мы вообще ничего не должны такого в интерфейсе описывать по типу точности и текста ошибки. Прятать её в абстрактный класс? В требованиях дан именно интерфейс.

2023-05-06 11:08 UTC, Dikin01 commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +public class MainWindowViewModel : ViewModelBase, INotifyDataErrorInfo
Пока валидация "маленькая" нет смысла в отдельный класс пихать. Перенести проверку во вспомогательный класс, по типу fluent Validation не сложно и быстро, но усложнит обычный калькулятор.

2023-05-06 11:09 UTC, Dikin01 commented on CalculatorBase/Styles/ValidationStyles.axaml
> +                        <!-- ReSharper disable once Xaml.CompiledBindingMissingDataTypeErrorHighlighting -->
А если я не пользуюсь ReSharperом?)

2023-05-06 11:13 UTC, dolbilov commented on CalculatorBase/Styles/ValidationStyles.axaml
> +                        <!-- ReSharper disable once Xaml.CompiledBindingMissingDataTypeErrorHighlighting -->
Тогда комментарий тебе не мешает :)

2023-05-06 11:14 UTC, Dikin01 commented on Tests/Tests.csproj
> +        <PackageReference Include="coverlet.collector" Version="3.2.0">
Да, не хочется лишнее пихать в зависимости. Потом может акнуться при сборке и при добавлении проектов

2023-05-06 11:16 UTC, ArtyuhovVadim commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +    public static IEnumerable AvailableOperations => Enum.GetValues<Operation>();
Можно вынести в расширения разметки

2023-05-06 11:16 UTC, ArtyuhovVadim commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +    }
Странно получается, у тебя оба аргумента типа double, но результат строка. Я бы конвертировал значения в строку и обратно на стороне разметки, а если в коде понадобится результат в виде числа, то нужно будет постоянно его переводить из строки в double

2023-05-06 11:21 UTC, ArtyuhovVadim commented on CalculatorBase/Styles/ValidationStyles.axaml
> +                        <!-- ReSharper disable once Xaml.CompiledBindingMissingDataTypeErrorHighlighting -->
Вообще их лучше так не оставлять, просто в настройках решарпера отключи эту проверку

2023-05-06 11:22 UTC, dolbilov commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +    }
При делении на 0 я просто устанавливаю туда `null`. Поэтому сделал строку. Думаешь, плохая идея?

2023-05-06 11:24 UTC, ArtyuhovVadim commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +    }
Ты можешь с таким же успехом использовать `double?` вместо `string?`

2023-05-06 19:32 UTC, devTryer31 commented on CalculatorBase/Interfaces/ICalculator.cs
> +    public const double Epsilon = 1e-6;
Я рассматривал этот вопрос в бесконтекстной форме. Если в требованиях было действительно задано так, то вопросов не имею.

2023-05-07 07:11 UTC, Dikin01 commented on CalculatorBase/Styles/ValidationStyles.axaml
> +                        <!-- ReSharper disable once Xaml.CompiledBindingMissingDataTypeErrorHighlighting -->
> Тогда комментарий тебе не мешает :)

Как раз мешает. И если возможно, то нужно просто настроить свой решарпер. Ты же папки .idea добавляешь в gitignore, тут похожий принцип

2023-05-07 07:21 UTC, Dikin01 commented on .github/workflows/dotnet.yml
> +          dotnet-version: 6.0.x
Что оно собирается тут - везение.
Ну представь, что приходит девопс какой-нибудь, и смотрит твой yml. Он будет думать, что у вас net6. Поставит на ваш локальный сервер только net6 sdk и при переносе твоего проекта на настоящий CI сборка будет падать.
Представь, что выйдет новый net8, ты повысишь версию проекта, а про сборку забудешь, так как "все прекрасно" собиралось. И у тебя всё упадёт.

2023-05-07 07:33 UTC, Dikin01 commented on Tests/CalculatorTests.cs
> +    public void Divide_ShouldReturnExpected(double a, double b, double expected)
Какой пользователь? Тут нет пользователя твоего приложения. Тут тесты модуля калькулятор, а не VM калькулятора. Завтра захочу твой экземпляр класса калькулятор добавить в свой класс для численного нахождения пределов, несобственных интегралов и так далее. И мне придётся тебе такие аргументы подавать как double.PositiveInfinity NegativeInfinity. Какое поведение будем ожидать без этих тестов?

2023-05-07 07:34 UTC, Dikin01 commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +    public static IEnumerable AvailableOperations => Enum.GetValues<Operation>();
А если у меня View - это консоль?

2023-05-07 09:47 UTC, ArtyuhovVadim commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +    public static IEnumerable AvailableOperations => Enum.GetValues<Operation>();
Справедливо, об этом я не подумал)

2023-05-08 13:05 UTC, dolbilov commented on .github/workflows/dotnet.yml
> +          dotnet-version: 6.0.x
Обновил.

2023-05-08 13:20 UTC, dolbilov commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +        if (Math.Abs(SecondArgument) < ICalculator.Epsilon)
Сделано.

2023-05-08 13:39 UTC, dolbilov commented on CalculatorBase/ViewModels/MainWindowViewModel.cs
> +    }
Очень ценное замечание, поправил.

2023-05-08 13:40 UTC, merged

2023-05-08 13:44 UTC, Dikin01 commented
Не забудь скваш коммитов сделать, если так много их плодишь